# Generated by Django 2.2 on 2019-04-18 21:39

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('longDescription', models.TextField(max_length=50)),
                ('ingredients', jsonfield.fields.JSONField()),
                ('tips', models.TextField(max_length=50)),
                ('foodinstructions', models.CharField(max_length=20)),
                ('shortdescription', models.TextField(max_length=50)),
                ('user', models.CharField(max_length=20)),
            ],
        ),
    ]
